name: Avatar_Test
favicon: null
layout_spectrum: 0.53084
typography_spectrum: 0.43833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b50000'
    - '#a56b6b'
    - '#e8b2b2'
    - '#3d3d3d'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.9375
  rhythmicContrast: 1
purpose:
  - name: awareness
    item: null
    url: null
